### ISSUE TITLE
Improve API UX when incorrect vhost specified

### ISSUE THREAD

**Issue by nvllsvm** [gmr/aiorabbit#7]
**Current**
A `StateTransitionError` exception is raised when connecting with an incorrect/non-existent vhost.

```
Traceback (most recent call last):
  File "/home/ar/code/aiorabbit_issues/issue_unclear_exception_missing_vhost.py", line 50, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ar/code/aiorabbit_issues/issue_unclear_exception_missing_vhost.py", line 46, in main
    await client.connect()
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/client.py", line 411, in connect
    await self._connect()
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/client.py", line 1421, in _connect
    if await self._channel0.open(self._transport):
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/channel0.py", line 177, in open
    result = await self._wait_on_state(
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/state.py", line 123, in _wait_on_state
    raise exc
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/client.py", line 1458, in _on_frame
    self._channel0.process(value)
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/channel0.py", line 156, in process
    self._set_state(STATE_CLOSE_RECEIVED)
  File "/home/ar/.local/share/virtualenvs/8774ac84884bd7b18658b2b29f968d87eb75cfeacd94119606eb487e954cfcef/lib/python3.9/site-packages/aiorabbit/state.py", line 84, in _set_state
    raise exceptions.StateTransitionError(
aiorabbit.exceptions.StateTransitionError: Invalid state transition from 'Open Sent' to 'Connection Close Received'
```

**Desired**
Ideal would be an exception indicating that the vhost is invalid. Otherwise, a dedicated connection error would be clearer than the current.

**Replicating**
Start rabbitmq locally with `docker run --rm --net=host rabbitmq:management-alpine`

Then run the following Python 
```
import asyncio

import aiorabbit
import aiorabbit.client


async def main():
    # works fine
    client = aiorabbit.client.Client('amqp://guest:guest@localhost:5672/%2f')
    await client.connect()

    # incorrect vhost
    client = aiorabbit.client.Client('amqp://guest:guest@localhost:5672/fakevhost')
    await client.connect()


if __name__ == '__main__':
    asyncio.run(main())
```

**Versions**
OS: Arch Linux
Kernel: Linux 5.12.10-zen1-1
Python: 3.9.5
aiorabbit: 1.0.0a1

**Comment by taoshiyu** [comment]
my rabbit url is correct (work fine with rabbitpy),but still raise this exception.i don't know why

**Comment by gmr** [comment]
@taoshiyu i need more info and think this is a different issue. Can you provide the traceback?

**Comment by gmr** [comment]
@nvllsvm this should have been raising an `aiorabbit.exceptions.NotAllowed` exception and has been fixed.

@taoshiyu please provide a working example of your problem and a valid traceback in another ticket.
